baseURL = "https://robert-dordai.github.io/"
title = ""
theme = "no-style-please"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
publishDir = "docs"

[params]
  description = "Your site description"
  copyright = "© 2023 Robert Dordai"
  dark = "true"
  highlight = true

[menu]


[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true