baseURL = "https://robert-dordai.github.io/"
title = ""
theme = "no-style-please"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
publishDir = "docs"

[params]
  description = "Your site description"
  copyright = "© 2023 Robert Dordai"
  dark = "true"
  highlight = true
  [params.theme_config]
    appearance = "dark"
    back_home_text = ".."
    date_format = "2006-01-02"
    show_description = false

[menu]

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true