baseURL = "https://robert-dordai.github.io/"
title = "Home"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
publishDir = "docs"

[params]
  description = "Your site description"
  copyright = "© 2023 Robert Dordai"
  dark = "auto"
  highlight = true

[menu]


[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true